-- Supabase Database Webhook & pg_net Trigger for Railway Worker
-- Sets up automatic task processing when tasks are created in Supabase.
--
-- Option 1: Supabase Dashboard UI Webhook:
-- Dashboard → Database → Webhooks → Create a new webhook:
--   Name: notify-worker-on-new-task
--   Table: tasks
--   Events: INSERT, UPDATE
--   Type: HTTP Request
--   URL: https://agentie-production.up.railway.app/enqueue
--   Method: POST
--   Headers: Content-Type: application/json
--   Payload: {"taskId": "{{record.id}}"}
--
-- Option 2: Run in Supabase SQL Editor:
-- create extension if not exists "pg_net";
-- create or replace function notify_railway_worker_task_pending()
-- returns trigger as $$
-- begin
--   if new.status = 'pending' then
--     perform net.http_post(
--       url := 'https://agentie-production.up.railway.app/enqueue',
--       headers := '{"Content-Type": "application/json"}'::jsonb,
--       body := json_build_object('taskId', new.id, 'agentId', new.agent_id, 'userId', new.user_id)::jsonb
--     );
--   end if;
--   return new;
-- end;
-- $$ language plpgsql;
--
-- create or replace trigger trg_notify_worker_task_pending
-- after insert or update of status on tasks
-- for each row
-- execute function notify_railway_worker_task_pending();
