import { Document, Packer, Paragraph } from "docx";
import ExcelJS from "exceljs";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import PptxGenJS from "pptxgenjs";

export const FILE_MIME_TYPES = {
  txt: "text/plain", md: "text/markdown", json: "application/json", csv: "text/csv", html: "text/html",
  docx: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  xlsx: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  pptx: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  pdf: "application/pdf",
};

export function fileExtension(name = "file.txt") {
  return String(name).toLowerCase().match(/\.([a-z0-9]+)$/)?.[1] || "txt";
}

function pdfSafeText(value) {
  return String(value || "")
    .replace(/[“”]/g, '"').replace(/[‘’]/g, "'")
    .replace(/[–—]/g, "-").replace(/…/g, "...")
    .replace(/[•◦▪]/g, "-").replace(/\u00a0/g, " ")
    .replace(/^\s{0,3}#{1,6}\s+/gm, "").replace(/\*\*|__/g, "")
    .normalize("NFKD").replace(/[\u0300-\u036f]/g, "")
    .replace(/[^\x20-\x7E\xA0-\xFF]/g, "");
}

function wrapPdfLine(font, value, size, maxWidth) {
  const line = pdfSafeText(value);
  if (!line) return [""];
  const words = line.split(/\s+/); const lines = []; let current = "";
  for (const word of words) {
    const candidate = current ? `${current} ${word}` : word;
    if (font.widthOfTextAtSize(candidate, size) <= maxWidth) { current = candidate; continue; }
    if (current) lines.push(current);
    if (font.widthOfTextAtSize(word, size) <= maxWidth) { current = word; continue; }
    let fragment = "";
    for (const char of word) {
      if (font.widthOfTextAtSize(fragment + char, size) > maxWidth && fragment) { lines.push(fragment); fragment = char; }
      else fragment += char;
    }
    current = fragment;
  }
  if (current || !lines.length) lines.push(current);
  return lines;
}

function parseDelimitedLine(line) {
  const cells = []; let value = ""; let quoted = false;
  for (let index = 0; index < line.length; index += 1) {
    const char = line[index];
    if (char === '"' && quoted && line[index + 1] === '"') { value += '"'; index += 1; }
    else if (char === '"') quoted = !quoted;
    else if ((char === "," || char === "\t") && !quoted) { cells.push(value.trim()); value = ""; }
    else value += char;
  }
  cells.push(value.trim()); return cells;
}

function spreadsheetRows(text) {
  try {
    const parsed = JSON.parse(text);
    if (Array.isArray(parsed) && parsed.length && parsed.every(item => item && typeof item === "object" && !Array.isArray(item))) {
      const headers = [...new Set(parsed.flatMap(item => Object.keys(item)))];
      return [headers, ...parsed.map(item => headers.map(header => item[header] ?? ""))];
    }
    if (Array.isArray(parsed)) return parsed.map(item => Array.isArray(item) ? item : [item]);
  } catch {}
  const lines = text.split(/\r?\n/).filter(line => line.trim());
  const markdownTable = lines.filter(line => /^\s*\|.*\|\s*$/.test(line));
  if (markdownTable.length >= 2) {
    return markdownTable
      .filter(line => !/^\s*\|?\s*:?-{3,}/.test(line))
      .map(line => line.trim().replace(/^\||\|$/g, "").split("|").map(cell => cell.trim()));
  }
  return lines.map(parseDelimitedLine);
}

async function encodePresentation(text) {
  const pptx = new PptxGenJS(); pptx.layout = "LAYOUT_WIDE"; pptx.author = "Agentie"; pptx.subject = "Generated by Agentie";
  const lines = text.split(/\r?\n/).map(line => line.trim()).filter(Boolean);
  const title = (lines.shift() || "Presentation").replace(/^#{1,6}\s*/, "").replace(/\*\*/g, "").slice(0, 100);
  const points = lines.map(line => line.replace(/^[-*•]\s*/, "").replace(/^#{1,6}\s*/, "").replace(/\*\*/g, "")).filter(Boolean);
  const chunks = []; for (let index = 0; index < Math.max(1, points.length); index += 6) chunks.push(points.slice(index, index + 6));
  for (let index = 0; index < chunks.length; index += 1) {
    const slide = pptx.addSlide(); slide.background = { color: "0B0B0E" };
    slide.addText(index === 0 ? title : `${title} · ${index + 1}`, { x: 0.7, y: 0.55, w: 11.9, h: 0.55, fontFace: "Arial", fontSize: 24, bold: true, color: "FFFFFF", margin: 0 });
    if (chunks[index].length) slide.addText(chunks[index].map(point => ({ text: point, options: { bullet: { indent: 18 }, breakLine: true } })), { x: 0.9, y: 1.45, w: 11.4, h: 5.3, fontFace: "Arial", fontSize: 18, color: "D8D8DE", breakLine: false, valign: "top", margin: 0.08, paraSpaceAfterPt: 14 });
    else slide.addText("Created with Agentie", { x: 0.9, y: 1.6, w: 11, h: 0.5, fontFace: "Arial", fontSize: 18, color: "A0A0AA", margin: 0 });
  }
  return Buffer.from(await pptx.write({ outputType: "nodebuffer", compression: true }));
}

export async function encodeGeneratedFile(name, content) {
  const extension = fileExtension(name);
  const text = typeof content === "string" ? content : JSON.stringify(content, null, 2);
  if (["txt", "md", "json", "csv", "html"].includes(extension)) {
    return { extension, text, buffer: Buffer.from(text, "utf8") };
  }
  if (extension === "docx") {
    const document = new Document({ sections: [{ children: text.split(/\r?\n/).map((line) => new Paragraph(line)) }] });
    return { extension, text, buffer: Buffer.from(await Packer.toBuffer(document)) };
  }
  if (extension === "xlsx") {
    const workbook = new ExcelJS.Workbook();
    const sheet = workbook.addWorksheet("Sheet 1");
    for (const row of spreadsheetRows(text)) sheet.addRow(row);
    if (sheet.rowCount) {
      sheet.getRow(1).font = { bold: true };
      sheet.views = [{ state: "frozen", ySplit: 1 }];
      sheet.columns.forEach(column => { column.width = Math.min(42, Math.max(10, ...column.values.slice(1).map(value => String(value ?? "").length + 2))); });
    }
    return { extension, text, buffer: Buffer.from(await workbook.xlsx.writeBuffer()) };
  }
  if (extension === "pptx") return { extension, text, buffer: await encodePresentation(text) };
  if (extension === "pdf") {
    const pdf = await PDFDocument.create();
    const font = await pdf.embedFont(StandardFonts.Helvetica);
    let page = pdf.addPage();
    let y = page.getHeight() - 48;
    for (const paragraph of text.split(/\r?\n/)) {
      for (const line of wrapPdfLine(font, paragraph, 11, page.getWidth() - 80)) {
        if (y < 48) { page = pdf.addPage(); y = page.getHeight() - 48; }
        page.drawText(line, { x: 40, y, size: 11, font, color: rgb(0, 0, 0) });
        y -= 16;
      }
    }
    return { extension, text, buffer: Buffer.from(await pdf.save()) };
  }
  throw new Error(`Unsupported file type .${extension}`);
}
