// ============================================================================
// AGENTIE CONNECTOR REGISTRY
// Real provider execution. No simulated success responses.
// ============================================================================
import axios from "axios";
import { supabaseAdmin } from "../supabaseClient.js";
import { decrypt } from "../lib/crypto.js";

export const CONNECTORS = {
  gmail: { id: "gmail", name: "Gmail", actions: { searchEmails: { name: "searchEmails", irreversible: false, description: "Search emails" }, readThread: { name: "readThread", irreversible: false, description: "Read an email thread" }, draftEmail: { name: "draftEmail", irreversible: false, description: "Create an email draft" }, sendEmail: { name: "sendEmail", irreversible: true, description: "Send an email" } } },
  gcal: { id: "gcal", name: "Google Calendar", actions: { checkAvailability: { name: "checkAvailability", irreversible: false, description: "Check calendar events" }, createMeeting: { name: "createMeeting", irreversible: true, description: "Create a calendar event" } } },
  slack: { id: "slack", name: "Slack", actions: { readChannel: { name: "readChannel", irreversible: false, description: "Read channel history" }, sendMessage: { name: "sendMessage", irreversible: true, description: "Send a Slack message" } } },
  github: { id: "github", name: "GitHub", actions: { searchRepos: { name: "searchRepos", irreversible: false, description: "Search repositories" }, readIssue: { name: "readIssue", irreversible: false, description: "Read an issue or pull request" }, createIssue: { name: "createIssue", irreversible: false, description: "Create an issue" }, mergePullRequest: { name: "mergePullRequest", irreversible: true, description: "Merge a pull request" } } },
  notion: { id: "notion", name: "Notion", actions: { searchPages: { name: "searchPages", irreversible: false, description: "Search Notion" }, readDoc: { name: "readDoc", irreversible: false, description: "Read a Notion page" }, createPage: { name: "createPage", irreversible: false, description: "Create a Notion page" }, deletePage: { name: "deletePage", irreversible: true, description: "Delete a Notion page" } } },
  gdrive: { id: "gdrive", name: "Google Drive", actions: { searchFiles: { name: "searchFiles", irreversible: false, description: "Search Google Drive" }, getFile: { name: "getFile", irreversible: false, description: "Read Google Drive file metadata or content" }, createFile: { name: "createFile", irreversible: false, description: "Create a Google Drive file" }, updateFile: { name: "updateFile", irreversible: false, description: "Update Google Drive file metadata" }, deleteFile: { name: "deleteFile", irreversible: true, description: "Delete a Google Drive file" } } },
  canva: { id: "canva", name: "Canva", actions: { searchDesigns: { name: "searchDesigns", irreversible: false, description: "Search the user's Canva designs" }, getDesign: { name: "getDesign", irreversible: false, description: "Get Canva design metadata and links" }, createDesign: { name: "createDesign", irreversible: false, description: "Create a Canva design" }, listBrandTemplates: { name: "listBrandTemplates", irreversible: false, description: "Search accessible Canva brand templates" }, getBrandTemplate: { name: "getBrandTemplate", irreversible: false, description: "Get Canva brand template metadata" } } },
  whatsapp: { id: "whatsapp", name: "WhatsApp Business", actions: { sendMessage: { name: "sendMessage", irreversible: true, description: "Send a WhatsApp message" }, getBusinessProfile: { name: "getBusinessProfile", irreversible: false, description: "Read WhatsApp business profile" } } },
  stripe: { id: "stripe", name: "Stripe", actions: { getInvoice: { name: "getInvoice", irreversible: false, description: "Inspect a Stripe invoice" }, createInvoice: { name: "createInvoice", irreversible: false, description: "Create a Stripe draft invoice" }, chargeCustomer: { name: "chargeCustomer", irreversible: true, description: "Create a Stripe payment intent" } } },
  shopify: { id: "shopify", name: "Shopify", actions: { getShop: { name: "getShop", irreversible: false, description: "Read Shopify shop information" }, searchProducts: { name: "searchProducts", irreversible: false, description: "Search Shopify products" }, searchOrders: { name: "searchOrders", irreversible: false, description: "Search Shopify orders" }, createProduct: { name: "createProduct", irreversible: false, description: "Create a Shopify product" } } },
  agentmail: { id: "agentmail", name: "AgentMail", actions: { listInboxes: { name: "listInboxes", irreversible: false, description: "List the agent's email inboxes" }, createInbox: { name: "createInbox", irreversible: false, description: "Create an email inbox for an agent" }, getInbox: { name: "getInbox", irreversible: false, description: "Get an agent email inbox" }, listMessages: { name: "listMessages", irreversible: false, description: "List messages in an agent inbox" }, searchMessages: { name: "searchMessages", irreversible: false, description: "Search messages in an agent inbox" }, getMessage: { name: "getMessage", irreversible: false, description: "Read an agent email" }, sendMessage: { name: "sendMessage", irreversible: true, description: "Send email from an agent inbox" }, replyToMessage: { name: "replyToMessage", irreversible: true, description: "Reply to an agent email" } } }
};

function parseCredentialValues(credentials) {
  const source = credentials?.values && typeof credentials.values === "object" ? credentials.values : credentials;
  const result = {};
  if (!source || typeof source !== "object") return result;
  for (const [key, value] of Object.entries(source)) {
    if (value === null || value === undefined) continue;
    if (typeof value === "string") {
      try { result[key] = decrypt(value); } catch { result[key] = value; }
    } else result[key] = value;
  }
  return result;
}

async function connectionFor(userId, connectorId) {
  const { data, error } = await supabaseAdmin.from("user_plugins").select("credentials,status").eq("user_id", userId).eq("plugin_id", connectorId).maybeSingle();
  if (error) throw new Error(`Unable to load ${connectorId} connection: ${error.message}`);
  if (!data || data.status !== "active") throw new Error(`${connectorId} is not connected for this user`);
  const credentials = parseCredentialValues(data.credentials);
  if (!Object.keys(credentials).length) throw new Error(`${connectorId} has no usable credentials configured`);
  return credentials;
}

function auth(token) { return { Authorization: `Bearer ${token}` }; }

function gmailRaw({ to, subject, body }) { return Buffer.from([`To: ${to}`, `Subject: ${subject || ""}`, "Content-Type: text/plain; charset=utf-8", "", body || ""].join("\r\n")).toString("base64url"); }
async function gmail(a,p,t){const h=auth(t);if(a==="searchEmails"){const r=await axios.get("https://gmail.googleapis.com/gmail/v1/users/me/messages",{headers:h,params:{q:p.query||"",maxResults:p.maxResults||20}});const messages=await Promise.all((r.data.messages||[]).slice(0,20).map(({id})=>axios.get(`https://gmail.googleapis.com/gmail/v1/users/me/messages/${id}`,{headers:h,params:{format:"metadata",metadataHeaders:["From","To","Subject","Date"]}}).then(x=>x.data)));return{messages,resultSizeEstimate:r.data.resultSizeEstimate||0};}if(a==="readThread")return(await axios.get(`https://gmail.googleapis.com/gmail/v1/users/me/threads/${encodeURIComponent(p.threadId)}`,{headers:h,params:{format:"full"}})).data;if(a==="draftEmail")return(await axios.post("https://gmail.googleapis.com/gmail/v1/users/me/drafts",{message:{raw:gmailRaw(p)}},{headers:{...h,"Content-Type":"application/json"}})).data;if(a==="sendEmail")return(await axios.post("https://gmail.googleapis.com/gmail/v1/users/me/messages/send",{raw:gmailRaw(p)},{headers:{...h,"Content-Type":"application/json"}})).data;}
async function gcal(a,p,t){const h=auth(t);if(a==="checkAvailability")return{events:(await axios.get("https://www.googleapis.com/calendar/v3/calendars/primary/events",{headers:h,params:{timeMin:p.timeMin,timeMax:p.timeMax,singleEvents:true,orderBy:"startTime",maxResults:p.maxResults||100}})).data.items||[]};if(a==="createMeeting")return(await axios.post("https://www.googleapis.com/calendar/v3/calendars/primary/events",{summary:p.summary,description:p.description,start:p.start,end:p.end,attendees:(p.attendees||[]).map(e=>typeof e==="string"?{email:e}:e)},{headers:{...h,"Content-Type":"application/json"}})).data;}
async function slack(a,p,t){const h={...auth(t),"Content-Type":"application/json; charset=utf-8"};if(a==="readChannel"){const r=await axios.get("https://slack.com/api/conversations.history",{headers:h,params:{channel:p.channelId,limit:p.limit||50,cursor:p.cursor}});if(!r.data.ok)throw new Error(r.data.error||"Slack history request failed");return r.data;}if(a==="sendMessage"){const r=await axios.post("https://slack.com/api/chat.postMessage",{channel:p.channelId,text:p.text,thread_ts:p.threadTs},{headers:h});if(!r.data.ok)throw new Error(r.data.error||"Slack send failed");return r.data;}}
async function github(a,p,t){const h={...auth(t),Accept:"application/vnd.github+json","X-GitHub-Api-Version":"2022-11-28"};if(a==="searchRepos")return(await axios.get("https://api.github.com/search/repositories",{headers:h,params:{q:p.query,per_page:p.perPage||20}})).data;if(a==="readIssue")return(await axios.get(`https://api.github.com/repos/${p.owner}/${p.repo}/issues/${p.issueNumber}`,{headers:h})).data;if(a==="createIssue")return(await axios.post(`https://api.github.com/repos/${p.owner}/${p.repo}/issues`,{title:p.title,body:p.body,labels:p.labels},{headers:h})).data;if(a==="mergePullRequest")return(await axios.put(`https://api.github.com/repos/${p.owner}/${p.repo}/pulls/${p.pullNumber}/merge`,{commit_title:p.commitTitle,commit_message:p.commitMessage,merge_method:p.mergeMethod||"merge"},{headers:h})).data;}
async function notion(a,p,t){const h={...auth(t),"Content-Type":"application/json","Notion-Version":"2022-06-28"};if(a==="searchPages")return(await axios.post("https://api.notion.com/v1/search",{query:p.query||"",page_size:p.pageSize||20},{headers:h})).data;if(a==="readDoc")return(await axios.get(`https://api.notion.com/v1/pages/${p.pageId}`,{headers:h})).data;if(a==="createPage")return(await axios.post("https://api.notion.com/v1/pages",{parent:p.parent,properties:p.properties,children:p.children},{headers:h})).data;if(a==="deletePage")return(await axios.patch(`https://api.notion.com/v1/pages/${p.pageId}`,{archived:true},{headers:h})).data;}
async function gdrive(a,p,t){const h=auth(t);if(a==="searchFiles")return(await axios.get("https://www.googleapis.com/drive/v3/files",{headers:h,params:{q:p.query||"trashed = false",pageSize:p.pageSize||50,fields:"files(id,name,mimeType,size,modifiedTime,webViewLink,parents),nextPageToken"}})).data;if(a==="getFile")return(await axios.get(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(p.fileId)}`,{headers:h,params:{alt:p.download?"media":"json",fields:p.download?undefined:"id,name,mimeType,size,modifiedTime,webViewLink"}})).data;if(a==="createFile")return(await axios.post("https://www.googleapis.com/drive/v3/files",{name:p.name,mimeType:p.mimeType,parents:p.parents},{headers:{...h,"Content-Type":"application/json"},params:{fields:"id,name,mimeType,webViewLink"}})).data;if(a==="updateFile")return(await axios.patch(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(p.fileId)}`,{name:p.name,description:p.description},{headers:{...h,"Content-Type":"application/json"},params:{fields:"id,name,mimeType,modifiedTime,webViewLink"}})).data;if(a==="deleteFile")return(await axios.delete(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(p.fileId)}`,{headers:h})).data;}
async function canva(a,p,t){const h=auth(t);if(a==="searchDesigns")return(await axios.get("https://api.canva.com/rest/v1/designs",{headers:h,params:{query:p.query,limit:p.limit||25,continuation:p.continuation}})).data;if(a==="getDesign")return(await axios.get(`https://api.canva.com/rest/v1/designs/${encodeURIComponent(p.designId)}`,{headers:h})).data;if(a==="createDesign")return(await axios.post("https://api.canva.com/rest/v1/designs",{design:p.design,asset_id:p.assetId,brand_template_id:p.brandTemplateId},{headers:{...h,"Content-Type":"application/json"}})).data;if(a==="listBrandTemplates")return(await axios.get("https://api.canva.com/rest/v1/brand-templates",{headers:h,params:{query:p.query,limit:p.limit||25,continuation:p.continuation}})).data;if(a==="getBrandTemplate")return(await axios.get(`https://api.canva.com/rest/v1/brand-templates/${encodeURIComponent(p.brandTemplateId)}`,{headers:h})).data;}
function parseSecret(raw){return raw && typeof raw === "object" ? raw : (()=>{try{return JSON.parse(raw);}catch{return{key:raw};}})();}
async function whatsapp(a,p,c){const token=c.accessToken||c.access_token||c.api_key||c.key,id=c.phoneNumberId||c.phone_number_id;if(!token||!id)throw new Error("WhatsApp requires access token and phone number ID");const base=`https://graph.facebook.com/v23.0/${encodeURIComponent(id)}`;if(a==="sendMessage")return(await axios.post(`${base}/messages`,{messaging_product:"whatsapp",recipient_type:"individual",to:p.to,type:"text",text:{preview_url:!!p.previewUrl,body:p.text}},{headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"}})).data;if(a==="getBusinessProfile")return(await axios.get(`${base}/whatsapp_business_profile`,{headers:{Authorization:`Bearer ${token}`},params:{fields:"about,address,description,email,profile_picture_url,websites,vertical"}})).data;}
async function stripe(a,p,c){const key=c.key||c.apiKey||c.api_key;if(!key)throw new Error("Stripe requires an API key");const h={Authorization:`Bearer ${key}`};if(a==="getInvoice")return(await axios.get(`https://api.stripe.com/v1/invoices/${encodeURIComponent(p.invoiceId)}`,{headers:h})).data;if(a==="createInvoice")return(await axios.post("https://api.stripe.com/v1/invoices",new URLSearchParams({customer:p.customerId,collection_method:p.collectionMethod||"send_invoice",days_until_due:String(p.daysUntilDue||30),description:p.description||""}),{headers:{...h,"Content-Type":"application/x-www-form-urlencoded"}})).data;if(a==="chargeCustomer")return(await axios.post("https://api.stripe.com/v1/payment_intents",new URLSearchParams({amount:String(p.amount),currency:p.currency||"usd",customer:p.customerId||"",payment_method:p.paymentMethodId||"",confirm:p.confirm?"true":"false"}),{headers:{...h,"Content-Type":"application/x-www-form-urlencoded"}})).data;}
async function shopify(a,p,c){const token=c.accessToken||c.access_token||c.api_key||c.key,shop=c.shop||c.shopDomain||c.store;if(!token||!shop)throw new Error("Shopify requires access token and shop domain");const host=String(shop).replace(/^https?:\/\//,"").replace(/\/$/,"");const url=`https://${host}/admin/api/2026-01/graphql.json`,h={"Content-Type":"application/json","X-Shopify-Access-Token":token};const q=async(query,variables={})=>{const r=await axios.post(url,{query,variables},{headers:h});if(r.data.errors?.length)throw new Error(r.data.errors.map(e=>e.message).join("; "));return r.data.data;};if(a==="getShop")return q(`query { shop { id name url myshopifyDomain } }`);if(a==="searchProducts")return q(`query($query:String){products(first:50,query:$query){edges{node{id title handle status totalInventory}}}}`,{query:p.query||""});if(a==="searchOrders")return q(`query($query:String){orders(first:50,query:$query){edges{node{id name createdAt displayFinancialStatus displayFulfillmentStatus totalPriceSet{shopMoney{amount currencyCode}}}}}}`,{query:p.query||""});if(a==="createProduct")return q(`mutation($input:ProductCreateInput!){productCreate(product:$input){product{id title handle status}userErrors{field message}}}`,{input:{title:p.title,descriptionHtml:p.descriptionHtml,vendor:p.vendor,productType:p.productType}});}
async function agentmail(a,p,c){const key=c.api_key||c.apiKey||c.key;if(!key)throw new Error("AgentMail requires an API key");const h={Authorization:`Bearer ${key}`,"Content-Type":"application/json"};const base="https://api.agentmail.to/v0";if(a==="listInboxes")return(await axios.get(`${base}/inboxes`,{headers:h,params:{limit:p.limit||50,page_token:p.pageToken,ascending:p.ascending}})).data;if(a==="createInbox")return(await axios.post(`${base}/inboxes`,{username:p.username,domain:p.domain,display_name:p.displayName,client_id:p.clientId,metadata:p.metadata},{headers:h})).data;if(a==="getInbox")return(await axios.get(`${base}/inboxes/${encodeURIComponent(p.inboxId)}`,{headers:h})).data;if(!p.inboxId)throw new Error("AgentMail inboxId is required for message actions");if(a==="listMessages")return(await axios.get(`${base}/inboxes/${encodeURIComponent(p.inboxId)}/messages`,{headers:h,params:{limit:p.limit||50,page_token:p.pageToken,from:p.from,to:p.to,subject:p.subject,after:p.after,before:p.before,ascending:p.ascending}})).data;if(a==="searchMessages")return(await axios.get(`${base}/inboxes/${encodeURIComponent(p.inboxId)}/messages/search`,{headers:h,params:{q:p.query||p.q||"",limit:p.limit||50,page_token:p.pageToken,after:p.after,before:p.before}})).data;if(a==="getMessage")return(await axios.get(`${base}/inboxes/${encodeURIComponent(p.inboxId)}/messages/${encodeURIComponent(p.messageId)}`,{headers:h})).data;if(a==="sendMessage")return(await axios.post(`${base}/inboxes/${encodeURIComponent(p.inboxId)}/messages/send`,{to:p.to,cc:p.cc,bcc:p.bcc,subject:p.subject,text:p.text,html:p.html,reply_to:p.replyTo,labels:p.labels,attachments:p.attachments,headers:p.headers},{headers:h})).data;if(a==="replyToMessage")return(await axios.post(`${base}/inboxes/${encodeURIComponent(p.inboxId)}/messages/${encodeURIComponent(p.messageId)}/reply`,{to:p.to,cc:p.cc,bcc:p.bcc,text:p.text,html:p.html,reply_to:p.replyTo,reply_all:!!p.replyAll,labels:p.labels,attachments:p.attachments,headers:p.headers},{headers:h})).data;}

export async function runAction(connectorId, actionName, params = {}, context = {}) {
  const connector = CONNECTORS[connectorId];
  if (!connector) throw new Error(`Connector '${connectorId}' not found in registry.`);
  const action = connector.actions[actionName];
  if (!action) throw new Error(`Action '${actionName}' not supported by connector '${connectorId}'.`);
  if (!context.userId) throw new Error("Connector action requires an authenticated user");
  const credentials = await connectionFor(context.userId, connectorId);
  let data;
  const token = credentials.access_token || credentials.accessToken || credentials.token || credentials.api_key || credentials.apiKey || credentials.key;
  if (["whatsapp","stripe","shopify","agentmail"].includes(connectorId)) {
    if (connectorId === "whatsapp") data = await whatsapp(actionName, params, credentials);
    if (connectorId === "stripe") data = await stripe(actionName, params, credentials);
    if (connectorId === "shopify") data = await shopify(actionName, params, credentials);
    if (connectorId === "agentmail") data = await agentmail(actionName, params, credentials);
  } else {
    if (!token) throw new Error(`${connectorId} has no access token in its connected credentials`);
    switch (connectorId) {
      case "gmail": data = await gmail(actionName, params, token); break;
      case "gcal": data = await gcal(actionName, params, token); break;
      case "slack": data = await slack(actionName, params, token); break;
      case "github": data = await github(actionName, params, token); break;
      case "notion": data = await notion(actionName, params, token); break;
      case "gdrive": data = await gdrive(actionName, params, token); break;
      case "canva": data = await canva(actionName, params, token); break;
      default: throw new Error(`Real execution is not wired for '${connectorId}' yet`);
    }
  }
  return { success: true, connector: connectorId, action: actionName, executedAt: new Date().toISOString(), data };
}
