import { supabaseAdmin } from "../supabaseClient.js";
import { Document, Packer, Paragraph } from "docx";
import ExcelJS from "exceljs";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import PptxGenJS from "pptxgenjs";

const MIME = {
  txt: "text/plain", md: "text/markdown", json: "application/json", csv: "text/csv", html: "text/html",
  docx: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  xlsx: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  pptx: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  pdf: "application/pdf",
};

function extOf(name = "file.txt") { const m = name.toLowerCase().match(/\.([a-z0-9]+)$/); return m?.[1] || "txt"; }
function safeName(name) { return String(name || "file.txt").replace(/[^a-zA-Z0-9._ -]/g, "_").slice(0, 180); }

function pdfSafeText(value) {
  return String(value || "").replace(/[“”]/g, '"').replace(/[‘’]/g, "'").replace(/[–—]/g, "-").replace(/…/g, "...")
    .replace(/[•◦▪]/g, "-").replace(/\u00a0/g, " ").replace(/^\s{0,3}#{1,6}\s+/gm, "").replace(/\*\*|__/g, "")
    .normalize("NFKD").replace(/[\u0300-\u036f]/g, "").replace(/[^\x20-\x7E\xA0-\xFF]/g, "");
}
function wrapPdfLine(font, value, size, maxWidth) {
  const line = pdfSafeText(value); if (!line) return [""];
  const words = line.split(/\s+/); const lines = []; let current = "";
  for (const word of words) {
    const candidate = current ? `${current} ${word}` : word;
    if (font.widthOfTextAtSize(candidate, size) <= maxWidth) { current = candidate; continue; }
    if (current) lines.push(current);
    if (font.widthOfTextAtSize(word, size) <= maxWidth) { current = word; continue; }
    let fragment = ""; for (const char of word) { if (font.widthOfTextAtSize(fragment + char, size) > maxWidth && fragment) { lines.push(fragment); fragment = char; } else fragment += char; }
    current = fragment;
  }
  if (current || !lines.length) lines.push(current); return lines;
}
function parseDelimitedLine(line) {
  const cells = []; let value = ""; let quoted = false;
  for (let index = 0; index < line.length; index += 1) { const char = line[index]; if (char === '"' && quoted && line[index + 1] === '"') { value += '"'; index += 1; } else if (char === '"') quoted = !quoted; else if ((char === "," || char === "\t") && !quoted) { cells.push(value.trim()); value = ""; } else value += char; }
  cells.push(value.trim()); return cells;
}
function spreadsheetRows(text) {
  try { const parsed = JSON.parse(text); if (Array.isArray(parsed) && parsed.length && parsed.every(item => item && typeof item === "object" && !Array.isArray(item))) { const headers = [...new Set(parsed.flatMap(item => Object.keys(item)))]; return [headers, ...parsed.map(item => headers.map(header => item[header] ?? ""))]; } if (Array.isArray(parsed)) return parsed.map(item => Array.isArray(item) ? item : [item]); } catch {}
  const lines = text.split(/\r?\n/).filter(line => line.trim()); const markdownTable = lines.filter(line => /^\s*\|.*\|\s*$/.test(line));
  if (markdownTable.length >= 2) return markdownTable.filter(line => !/^\s*\|?\s*:?-{3,}/.test(line)).map(line => line.trim().replace(/^\||\|$/g, "").split("|").map(cell => cell.trim()));
  return lines.map(parseDelimitedLine);
}
async function encodePresentation(text) {
  const pptx = new PptxGenJS(); pptx.layout = "LAYOUT_WIDE"; pptx.author = "Agentie"; pptx.subject = "Generated by Agentie";
  const lines = text.split(/\r?\n/).map(line => line.trim()).filter(Boolean); const title = (lines.shift() || "Presentation").replace(/^#{1,6}\s*/, "").replace(/\*\*/g, "").slice(0, 100);
  const points = lines.map(line => line.replace(/^[-*•]\s*/, "").replace(/^#{1,6}\s*/, "").replace(/\*\*/g, "")).filter(Boolean); const chunks = [];
  for (let index = 0; index < Math.max(1, points.length); index += 6) chunks.push(points.slice(index, index + 6));
  for (let index = 0; index < chunks.length; index += 1) { const slide = pptx.addSlide(); slide.background = { color: "0B0B0E" }; slide.addText(index === 0 ? title : `${title} · ${index + 1}`, { x: 0.7, y: 0.55, w: 11.9, h: 0.55, fontFace: "Arial", fontSize: 24, bold: true, color: "FFFFFF", margin: 0 }); if (chunks[index].length) slide.addText(chunks[index].map(point => ({ text: point, options: { bullet: { indent: 18 }, breakLine: true } })), { x: 0.9, y: 1.45, w: 11.4, h: 5.3, fontFace: "Arial", fontSize: 18, color: "D8D8DE", breakLine: false, valign: "top", margin: 0.08, paraSpaceAfterPt: 14 }); else slide.addText("Created with Agentie", { x: 0.9, y: 1.6, w: 11, h: 0.5, fontFace: "Arial", fontSize: 18, color: "A0A0AA", margin: 0 }); }
  return Buffer.from(await pptx.write({ outputType: "nodebuffer", compression: true }));
}

export async function encodeFile(name, content) {
  const ext = extOf(name);
  const text = typeof content === "string" ? content : JSON.stringify(content, null, 2);
  if (["txt", "md", "json", "csv", "html"].includes(ext)) return { buffer: Buffer.from(text, "utf8"), text };
  if (ext === "docx") {
    const doc = new Document({ sections: [{ children: text.split(/\r?\n/).map((line) => new Paragraph(line)) }] });
    return { buffer: Buffer.from(await Packer.toBuffer(doc)), text };
  }
  if (ext === "xlsx") {
    const wb = new ExcelJS.Workbook(); const ws = wb.addWorksheet("Sheet 1");
    for (const row of spreadsheetRows(text)) ws.addRow(row);
    if (ws.rowCount) { ws.getRow(1).font = { bold: true }; ws.views = [{ state: "frozen", ySplit: 1 }]; ws.columns.forEach(column => { column.width = Math.min(42, Math.max(10, ...column.values.slice(1).map(value => String(value ?? "").length + 2))); }); }
    return { buffer: Buffer.from(await wb.xlsx.writeBuffer()), text };
  }
  if (ext === "pptx") return { buffer: await encodePresentation(text), text };
  if (ext === "pdf") {
    const pdf = await PDFDocument.create(); const page = pdf.addPage(); const font = await pdf.embedFont(StandardFonts.Helvetica);
    const lines = text.split(/\r?\n/); let y = page.getHeight() - 48;
    for (const paragraph of lines) { for (const line of wrapPdfLine(font, paragraph, 11, page.getWidth() - 80)) { if (y < 48) { y = page.getHeight() - 48; pdf.addPage(); } const p = pdf.getPages()[pdf.getPageCount() - 1]; p.drawText(line, { x: 40, y, size: 11, font, color: rgb(0, 0, 0) }); y -= 16; } }
    return { buffer: Buffer.from(await pdf.save()), text };
  }
  throw new Error(`Unsupported file type .${ext}`);
}

export async function createFile({ userId, agentId, name, content }) {
  const filename = safeName(name); const { buffer, text } = await encodeFile(filename, content); const ext = extOf(filename);
  const { data, error } = await supabaseAdmin.from("agent_files").insert({
    user_id: userId, agent_id: agentId, name: filename, mime_type: MIME[ext] || "application/octet-stream", extension: ext,
    content_text: text, content_base64: buffer.toString("base64"), size_bytes: buffer.length,
  }).select("id,name,mime_type,extension,size_bytes,version,created_at,updated_at").single();
  if (error) throw error; return data;
}

export async function readFile({ userId, fileId, name }) {
  let q = supabaseAdmin.from("agent_files").select("*").eq("user_id", userId);
  q = fileId ? q.eq("id", fileId) : q.eq("name", safeName(name));
  const { data, error } = await q.single(); if (error || !data) throw new Error(error?.message || "File not found");
  return { ...data, content: data.content_text, download_base64: data.content_base64 };
}

export async function listFiles({ userId, agentId }) {
  let q = supabaseAdmin.from("agent_files").select("id,name,mime_type,extension,size_bytes,version,created_at,updated_at").eq("user_id", userId).order("updated_at", { ascending: false });
  if (agentId) q = q.eq("agent_id", agentId); const { data, error } = await q; if (error) throw error; return data || [];
}

export async function editFile({ userId, fileId, name, content }) {
  const current = await readFile({ userId, fileId, name });
  const filename = safeName(name || current.name); const { buffer, text } = await encodeFile(filename, content); const ext = extOf(filename);
  const { data, error } = await supabaseAdmin.from("agent_files").update({
    name: filename, mime_type: MIME[ext] || "application/octet-stream", extension: ext, content_text: text,
    content_base64: buffer.toString("base64"), size_bytes: buffer.length, version: (current.version || 1) + 1, updated_at: new Date().toISOString(),
  }).eq("id", current.id).eq("user_id", userId).select("id,name,mime_type,extension,size_bytes,version,created_at,updated_at").single();
  if (error) throw error; return data;
}

export async function runFileTool({ userId, agentId, action, params = {} }) {
  if (action === "create_file") return { ok: true, data: await createFile({ userId, agentId, ...params }) };
  if (action === "read_file") return { ok: true, data: await readFile({ userId, ...params }) };
  if (action === "list_files") return { ok: true, data: await listFiles({ userId, agentId }) };
  if (action === "edit_file") return { ok: true, data: await editFile({ userId, ...params }) };
  return { ok: false, error: `Unknown file action: ${action}` };
}
