import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import { requireAuth } from './lib/authMiddleware.js';
import pluginConnectionCompatRouter from './routes/pluginConnectionCompat.js';
import pluginsRouter, { oauthCallbackHandler } from './routes/plugins.js';
import agentsRouter from './routes/agents.js';
import tasksRouter from './routes/tasks.js';
import taskProgressRouter from './routes/taskProgress.js';
import parallelRouter from './routes/parallel.js';
import collaborationRouter from './routes/collaboration.js';
import chiefOfStaffRouter from './routes/chiefOfStaff.js';
import skillsRouter from './routes/skills.js';
import routinesRouter from './routes/routines.js';
import tokensRouter from './routes/tokens.js';
import systemRouter from './routes/system.js';
import filesRouter from './routes/files.js';
import summariesRouter from './routes/summaries.js';
import conversationsRouter from './routes/conversations.js';
import activityRouter from './routes/activity.js';
import toolManifestRouter from './routes/toolManifest.js';
import webhooksRouter from './routes/webhooks.js';
import memoryRouter from './routes/memory.js';
import { cronScheduler } from './services/cronScheduler.js';
import { refreshModelsCatalog } from './services/modelCatalogService.js';
import { rateLimit } from './lib/rateLimit.js';
import { configuredCorsOrigins, isAllowedCorsOrigin } from './lib/corsPolicy.js';

const app = express();
const PORT = process.env.PORT || process.env.SERVER_PORT || 4000;
const configuredOrigins = configuredCorsOrigins();
app.use(cors({ origin(origin, callback) {
  if (isAllowedCorsOrigin(origin, configuredOrigins)) return callback(null, true);
  callback(new Error('Origin is not allowed by CORS'));
}, credentials: true }));
app.use(express.json({ limit: '10mb' }));
app.use('/api', rateLimit({ windowMs: 60_000, max: Number(process.env.API_RATE_LIMIT || 180) }));
app.get("/api/plugins/callback", oauthCallbackHandler);
app.use("/api/webhooks", webhooksRouter);
app.use("/api/plugins", requireAuth, pluginConnectionCompatRouter);
app.use("/api/plugins", requireAuth, pluginsRouter);
app.use("/api/agents", requireAuth, agentsRouter);
app.use("/api/tasks", requireAuth, tasksRouter);
app.use("/api/task-progress", requireAuth, taskProgressRouter);
app.use("/api/parallel", requireAuth, parallelRouter);
app.use("/api/collaboration", requireAuth, collaborationRouter);
app.use("/api/chief-of-staff", requireAuth, chiefOfStaffRouter);
app.use("/api/skills", requireAuth, skillsRouter);
app.use("/api/routines", requireAuth, routinesRouter);
app.use("/api/tokens", requireAuth, tokensRouter);
app.use("/api/system", requireAuth, systemRouter);
app.use("/api/files", requireAuth, filesRouter);
app.use("/api/summaries", requireAuth, summariesRouter);
app.use("/api/conversations", requireAuth, conversationsRouter);
app.use("/api/activity", requireAuth, activityRouter);
app.use("/api/memory", requireAuth, memoryRouter);
app.use("/api/tools", requireAuth, toolManifestRouter);
app.get('/health', (req, res) => res.json({ status: 'ok', service: 'Agentie Runtime Engine & AI Brain', openrouter_configured: !!process.env.OPENROUTER_API_KEY, time: new Date().toISOString() }));

app.listen(PORT, async () => {
  console.log(`⚡ [Agentie Backend] Running on http://localhost:${PORT}`);
  cronScheduler.start();
  await refreshModelsCatalog();
  setInterval(() => refreshModelsCatalog().catch((err) => console.error('[modelCatalog] periodic refresh failed:', err.message)), 12 * 60 * 60 * 1000);
});
