import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import { requireAuth } from './lib/authMiddleware.js';
import pluginConnectionCompatRouter from './routes/pluginConnectionCompat.js';
import pluginsRouter, { oauthCallbackHandler } from './routes/plugins.js';
import agentsRouter from './routes/agents.js';
import tasksRouter from './routes/tasks.js';
import taskProgressRouter from './routes/taskProgress.js';
import parallelRouter from './routes/parallel.js';
import collaborationRouter from './routes/collaboration.js';
import chiefOfStaffRouter from './routes/chiefOfStaff.js';
import skillsRouter from './routes/skills.js';
import routinesRouter from './routes/routines.js';
import tokensRouter from './routes/tokens.js';
import systemRouter from './routes/system.js';
import filesRouter from './routes/files.js';
import { cronScheduler } from './services/cronScheduler.js';
import { refreshModelsCatalog } from './services/modelCatalogService.js';

const app = express();
const PORT = process.env.PORT || process.env.SERVER_PORT || 4000;
app.use(cors());
app.use(express.json({ limit: '10mb' }));
app.get("/api/plugins/callback", oauthCallbackHandler);
app.use("/api/plugins", requireAuth, pluginConnectionCompatRouter);
app.use("/api/plugins", requireAuth, pluginsRouter);
app.use("/api/agents", requireAuth, agentsRouter);
app.use("/api/tasks", requireAuth, tasksRouter);
app.use("/api/task-progress", requireAuth, taskProgressRouter);
app.use("/api/parallel", requireAuth, parallelRouter);
app.use("/api/collaboration", requireAuth, collaborationRouter);
app.use("/api/chief-of-staff", requireAuth, chiefOfStaffRouter);
app.use("/api/skills", requireAuth, skillsRouter);
app.use("/api/routines", requireAuth, routinesRouter);
app.use("/api/tokens", requireAuth, tokensRouter);
app.use("/api/system", requireAuth, systemRouter);
app.use("/api/files", requireAuth, filesRouter);
app.get('/health', (req, res) => res.json({ status: 'ok', service: 'Agentie Runtime Engine & AI Brain', openrouter_configured: !!process.env.OPENROUTER_API_KEY, time: new Date().toISOString() }));

app.listen(PORT, async () => {
  console.log(`⚡ [Agentie Backend] Running on http://localhost:${PORT}`);
  cronScheduler.start();
  await refreshModelsCatalog();
  setInterval(() => refreshModelsCatalog().catch((err) => console.error('[modelCatalog] periodic refresh failed:', err.message)), 12 * 60 * 60 * 1000);
});
